[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Handle API routes if you have any
# [[redirects]]
#   from = "/api/*"
#   to = "https://react-blogb-2.onrender.com/api/:splat"
#   status = 200
